name: Deploy backend

on: workflow_call

# Example steps
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend
        run: echo 'Building backend, run unit tests, creating a docker image and publish it'

  deploy-satge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying of backend to stage/review app
        run: echo 'Deploying of backend'