name: TeamCity deployment

on: push

jobs:
  # Build back-end and deploy to stage/review app
  backend:
    uses: ./.github/workflows/backend-stage.yml

  # Build front-end and deploy to stage/review app
  frontend:
    uses: ./.github/workflows/frontend-stage.yml

  # Run API tests
  automation-api:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: api

  # Run UI tests
  automation-ui:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui

  manual-prod-approval:
    needs: [automation-api, automation-ui]
    runs-on: ubuntu-latest
    environment: : 'prod'
      steps:
        - name: Approve app to production
          run: echo Approved to production

  # Deploy backend and frontend to Prod
  deploy-prod:
    needs: manual-prod-approval
    uses: ./.github/workflows/deploy-prod.yml

